---
#Certificate Vars
acme_dir: "{{ local_path }}"
acme_keys_dir: "{{ local_path }}/keys"
acme_csrs_dir: "{{ local_path }}/csrs"
acme_certs_dir: "{{ local_path }}/certs"
acme_chain_dir: "{{ local_path }}/chain"
acme_private_key: "{{ acme_keys_dir }}/{{ host_name }}.{{ domain_name }}.key"
acme_csr: "{{ acme_csrs_dir }}/{{ host_name }}.{{ domain_name }}.csr"
acme_crt: "{{ acme_certs_dir }}/{{ item }}.crt"
acme_full_chain: "{{ acme_chain_dir }}/{{ item }}-fullchain.crt"
acme_chain: "{{ acme_chain_dir }}/{{ host_name }}.{{ domain_name }}-intermediate.crt"