---
- name: Include New Certificate
  include_tasks: new_cert.yml
  when: new_host == "yes"

- name: Find all .crt files in the directory
  find:
    paths: "{{ acme_certs_dir }}"
    patterns: "*.crt"
  register: crt_files
  when: new_host == "no"

- name: Set array variable with list of .crt files
  set_fact:
    crt_file_list: "{{ crt_files.files | map(attribute='path') | list }}"
  when: new_host == "no"

- name: Debug crt file list
  debug:
    var: crt_file_list
  when: debug_enable == "yes"

- name: Remove .crt string from certificate in the array
    set_fact:
      crt_file_list_clean: "{{ crt_file_list | map('regex_replace', .crt, '') | list }}"

- name: Debug cleaned up crt file list
  debug:
    var: crt_file_list_clean
  when: debug_enable == "yes"

- name: Include Daily Renew
  include_tasks: daily_renew.yml
  when: new_host == "no"
  loop: " {{ crt_file_list_clean }}"