---
- name: Ensure dnspython is installed
  ansible.builtin.pip:
    name: dnspython
    state: present
  become: yes
  when: new_host == "yes"

- name: Add new hosts DNS record if it does not exist
  community.general.nsupdate:
    server: "{{ internal_dns_server }}"
    zone: "{{ domain_name }}"
    record: "{{ host_name }}"
    value: "{{ host_ip }}"
    type: "A"
    ttl: 300
    key_name: "{{ internal_dns_user }}"
    key_secret: "{{ internal_dns_pass }}"
    key_algorithm: "hmac-sha256"
    state: present
  when: new_host == "yes"