download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-mysql-3.9.0.tar.gz
format_version: 1.0.0
name: mysql
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.9.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/mysql/versions/3.9.0/
