---
- name: set varaibles to import certifcates
  set_fact:
    acme_keys_dir: "{{ local_path }}/keys"
    acme_csrs_dir: "{{ local_path }}/csrs"
    acme_certs_dir: "{{ local_path }}/certs"
    acme_chain_dir: "{{ local_path }}/chain"
    
- name: Importing certificate
  dellemc.openmanage.idrac_certificates:
    idrac_ip: "{{ item }}"
    idrac_user: "{{ ipmi_user }}"
    idrac_password: "{{ ipmi_pass }}"
    ca_path: "{{ acme_chain_dir }}/{{ item }}-fullchain.crt"
    command: "import"
    certificate_type: "HTTPS"
    validate_certs: False
    certificate_path: "{{ acme_certs_dir }}/{{ item }}.crt"
    ssl_key: "{{ acme_keys_dir }}/{{ item }}.key"
  loop: "{{ ipmi_hosts }}"
  ignore_errors: yes