---
collections:
   - name: community.vmware
   - name: community.general
   - name: community.crypto
   - name: ansible.controller
   - name: ansible.eda
   - name: ansible.netcommon
   - name: ansible.network
   - name: ansible.posix
   - name: ansible.receptor
   - name: ansible.scm
   - name: ansible.security
   - name: ansible.snmp
   - name: ansible.tower
   - name: ansible.utils
   - name: ansible.windows
   - name: ansible.yang
   - name: redhat.amq_broker
   - name: redhat.data_grid
   - name: redhat.insights
   - name: redhat.insights_eda
   - name: redhat.jbcs
   - name: redhat.jws
   - name: redhat.openshift
   - name: redhat.redhat_csp_download
   - name: redhat.rhel_idm
   - name: redhat.rhel_system_roles
   - name: redhat.rhv
   - name: redhat.runtimes_common
   - name: redhat.sap_install
   - name: redhat.satellite
   - name: redhat.satellite_operations
   - name: redhat.sso
   - name: amazon.aws
   - name: google.cloud
   - name: azure.azcollection
   - name: dellemc.openmanage
