---
#Certificate Vars
acme_challenge_type: dns-01
acme_version: 2
acme_challenge_host: "_acme-challenge.{{ host_name }}.{{ domain_name }}."
acme_cn: "{{ host_name }}.{{ domain_name }}"
acme_dir: "{{ local_path }}"
acme_keys_dir: "{{ local_path }}/keys"
acme_csrs_dir: "{{ local_path }}/csrs"
acme_certs_dir: "{{ local_path }}/certs"
acme_chain_dir: "{{ local_path }}/chain"
acme_account_key: "{{ local_path }}/account/account.key"
acme_private_key: "{{ acme_keys_dir }}/{{ host_name }}.{{ domain_name }}.key"
acme_csr: "{{ acme_csrs_dir }}/{{ host_name }}.{{ domain_name }}.csr"
acme_crt: "{{ acme_certs_dir }}/{{ host_name }}.{{ domain_name }}.crt"
acme_full_chain: "{{ acme_chain_dir }}/{{ host_name }}.{{ domain_name }}-fullchain.crt"
acme_chain: "{{ acme_chain_dir }}/{{ host_name }}.{{ domain_name }}-intermediate.crt"

record_type: "TXT"
record_host: "_acme-challenge.{{host_name}}"
record_ttl: 300