---
- name: PXE Server Setup - Check for needed prerequisites
  package:
    name:
      - yum-utils
      - tftp-server
      - syslinux
      - httpd
    state: present
  when: ansible_os_family == 'RedHat'