---
- name: PXE Server Setup - Check for needed prerequisites
  package:
    name:
      - yum-utils
      - tftp-server
      - syslinux
      - httpd
      - nmstate
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install pyghmi
  pip:
    name: pyghmi
    state: present